### ISSUE TITLE
Feature Request / Addition : 'Thick' Slice Projection

### ISSUE THREAD

**Issue by PanosOik** [True-North-Intelligent-Algorithms/tnia-python#2]
Hello, I've been trying to plot orthogonal projections of 3D images and have found your plotting functions very useful. I wanted to replicate Imaris's extended orthogonal view (where one can pick an interval for each axis to do the max projection on, instead of a single slice or the entire volume) and made some minimal adjustments to your code to make that happen - just thought to share if it is of interest to anyone else -- I'm appending a link to a public colab notebook showing the differences. (also added layout = 'constrained' for the plot titles to be correctly displayed)

https://colab.research.google.com/drive/1rC-U72zaJZY9zBql8DcTNgSIXJaz9jIm?usp=sharing

Cheers,

**Comment by bnorthan** [comment]
Thanks a lot for contributing this.  I added it in this [commit](https://github.com/True-North-Intelligent-Algorithms/tnia-python/commit/9ef6d9303f26a76e2b42e892d04209e23d66a14f).

If you have any other suggestions to improve this or anything else let me know.

**Comment by PanosOik** [comment]
Thank you, will do!
