### ISSUE TITLE
Adding features to the interactive viewer (multichannel and "slabs")

### ISSUE THREAD

**Issue by eigenP** [True-North-Intelligent-Algorithms/tnia-python#3]
Hi Brian,

I have been playing around with your 3d plotting functions and added multi-channel support, and the thick "slab" projection, into your interactive (ipywidgets) function. I have made one incompatible change (adding a `vmin` kwarg), but otherwise I believe everything else plays nicely with what was already in there.

You can give it a quick try using this snippet: (e.g. on google colab)

```
!curl -O https://raw.githubusercontent.com/eigenP/utils/main/tnia_plotting_3d.py
from tnia_plotting_3d import show_xyz_max_slice_interactive

from skimage.data import cells3d

img_raw = cells3d()
membranes = img_raw[:,0,...]
nuclei = img_raw[:,1,...]


show_xyz_max_slice_interactive([membranes, nuclei],
                               gamma= [0.5, 1.0],
                               vmin = [0.05, 0.1],
                               vmax = [0.9, 1.],
                               sz = 1.0,
                               colors = ['limegreen', 'magenta'],
                               )
```

and the result should be this:
![Untitled](https://github.com/user-attachments/assets/a02ded9e-4a1e-4722-b5c1-e5a7ea31f8c1)

P.S. Lmk if it is bad policy to keep a copy of these functions in my repo

**Comment by bnorthan** [comment]
Hi @eigenP 

Thanks for the contribution.  This is really useful.  I will test it a bit and then can merge it to the main repo shortly.

No problem keeping your own copy.   It is licensed under the BSD license https://github.com/True-North-Intelligent-Algorithms/tnia-python.  The only requirement is that you redistribute a copy of the license, if you redistribute a derivative work.  I am honestly not too concerned about that (I am happy for anybody to use my open source code, any way they want and not too worried if the license is redistributed) however sometimes people do get concerned about it, so as a general practice it is good too check any open source repo for the license and follow the guidelines.   

Brian

**Comment by bnorthan** [comment]
Hi @eigenP 

Thank you so much for the awesome example.  I finally got around to working on the projections again and added a bunch of color related utilities, partly based on your examples. 

You can find your ```show_xyz_max_slice_interactive``` function [here](https://github.com/True-North-Intelligent-Algorithms/tnia-python/blob/main/tnia/plotting/interactive_projections.py#L168)

The only change I made is that I mix together the RGB image before slicing it.  See [here](https://github.com/True-North-Intelligent-Algorithms/tnia-python/blob/main/tnia/plotting/interactive_projections.py#L220).

You can find the function that creates the RGB image [here](https://github.com/True-North-Intelligent-Algorithms/tnia-python/blob/main/tnia/plotting/plt_helper.py#L244).  

I had been working on this but merged in a couple of your ideas.  For example my original implementation took in a list of stains (like 'FITC', 'DAPI' etc) and looked up colors from stains, but I also added in the option to take in a list of colors, as you did in your code. 

Finally I put your example code in a notebook [here](https://github.com/True-North-Intelligent-Algorithms/tnia-python/blob/main/notebooks/plotting/22_color_max_slice_interactive_stacks.ipynb). 

Let me know if you have any feedback.

**Comment by eigenP** [comment]
Cheers, thank you so much for this super useful library!
